### PR TITLE
Fix: several serious bugs

### LINKED ISSUE #43: Can't find path to partial
For the partials only, if we set partial path with "api/v1" prefix (as usual in jbuilder templates):
```ruby
json.contact project.contact, partial: "api/v1/contacts/contact", as: :contact

json.contact do
  json.partial! "api/v1/contacts/contact", contact: project.contact
end

json.goals do
  json.array! project.goals, partial: "api/v1/goals/goal", as: :goal
end
```
the partials cannot be found, because it looks in "app/views/api/v1/api/v1/contacts/contact".

However, if we set partial to just "contacts/contact", it looks only in "app/views" and never in "app/views/api/v1" (not mentioning that the real API stops working because the partial could not be found).

### LINKED ISSUE #47: Inline partials do not work
Inline arrays with partials also do not work:
```ruby
json.goals project.goals, partial: "api/v1/goals/goal", as: :goal
```
produces error:
```ruby
ActionView::Template::Error ({:partial=>"api/v1/goals/goal", :as=>:goal} is not a symbol nor a string)
```

### PR DESCRIPTION
**Pull request by newstler**
Fixes #43, #45, #46, #47, #48

### CODE REVIEW

File: lib/jbuilder/schema/template.rb [hunk 1]
```diff
@@ -59,7 +59,11 @@ def target!
     end
 
     def schema!
-      if ([@attributes] + @attributes.each_value.grep(::Hash)).any? { _1[:type] == :array && _1.key?(:items) }
+      # TODO: Not sure why it was like that, when it was meant to be used,
+      # but that seems to fix the problem with disappearance of root properties
+      # https://github.com/bullet-train-co/jbuilder-schema/issues/46
+      # if ([@attributes] + @attributes.each_value.grep(::Hash)).any? { _1[:type] == :array && _1.key?(:items) } # && 1 == 0
+      if ([@attributes] + @attributes.first.grep(::Hash)).any? { _1[:type] == :array && _1.key?(:items) } # && 1 == 0
```
Comment (newstler) [inline lib/jbuilder/schema/template.rb:66]: @kaspth Please take a look at those lines, do you have any idea why it was written so and can it be done better?

Comment (kaspth) [reply lib/jbuilder/schema/template.rb]: I just saw the final lines in the PR and this looks good to me!
