### PR TITLE
Fix: shared and custom partials

### LINKED ISSUE #51: `json.array!`'s `items` is generated wrong when it is not a reference
It would be convenient to add a custom version of that partial that is local to the template being rendered (for example, in `orders/_order.json.jbuilder` we want to inline just `:id` and `:name` of the segments.
Currently we have

```ruby
json.segments do
  json.array! order.workspace&.segments do |segment|
    json.id segment.id
    json.name segment.name
  end
end
```
Which results in invalid OpenAPI schema of
```yaml
segments:
  type:
  - array
  - 'null'
  items: []
  description: Segments
```
(where the `items: []` is invalid since it either expects a `$ref` or the properties to be listed)

Having a `orders/_segment.json.jbuilder` template that we could include with
```ruby
json.segments order.workspace&.segments, partial: "api/v2/orders/segment", as: :segment
```
might be better to be able to include those properties?

### LINKED ISSUE #52: Shared partial breaks doc generation
https://github.com/clickfunnels2/admin/pull/20857

Here we trying to add additional attributes into all templates by adding a shared partial - which breaks doc gen with `ArgumentError: unknown keyword: :resource`

### PR DESCRIPTION
**Pull request by newstler**
Fixes #52

### CODE REVIEW

File: lib/jbuilder/schema/template.rb [hunk 1]
```diff
@@ -254,5 +261,15 @@ def _merge_block(key)
       value = _object(value, _required!(value.keys)) unless value[:type] == :array || value.key?(:$ref)
       _merge_values(current_value, value)
     end
+
+    def _within_block?(&block)
+      block.present? && _one_line?(block.source)
```
Comment (kaspth) [inline lib/jbuilder/schema/template.rb:266]: iirc `source` comes from the `method_source` gem that Rails bundled, but maybe 7.1 doesn't bundle it anymore?

Though I'm wondering if we could the stacktrace via `caller_locations` to detect if we're within a block instead?

File: lib/jbuilder/schema/template.rb [hunk 2]
```diff
@@ -254,5 +261,15 @@ def _merge_block(key)
...
+    end
+
+    def _one_line?(text)
```
Comment (kaspth) [inline lib/jbuilder/schema/template.rb:269]: Why does it matter that a block is one line or not?
